[package]
authors = ["MODAP"]
name = "brain"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.3"
nalgebra = "0.29.0"
pylon-cxx = "0.3.3"
log = "0.4.17"
tokio-stream = "0.1.9"
v4l = "0.12.1"
tokio = { version = "1.12.0", features = ["full"] }

