[package]
authors = ["MODAP"]
edition = "2018"
name = "control"
version = "0.1.0"

[dependencies]
brain = { path = "../brain" }
mpu6050 = "0.1.4"
i2cdev = "0.5.1"
linux-embedded-hal = "0.3.2"
csv = "1.1.6"